version: "3.7"

services:
    database:
        image: mysql:5.7
        container_name: data
        ports:
            - 3306:3306
        expose: 
            - 3306
        environment: 
            - MYSQL_DATABASE=data
            - MYSQL_USER=nlw
            - MYSQL_PASSWORD=nlwtogether
            - MYSQL_ROOT_PASSWORD=nlwtogether
            - MYSQL_ALLOW_EMPTY_PASSWORD=nlwtogether
            - MYSQL_RANDOM_ROOT_PASSWORD=nlwtogether
        volumes: 
            - mysqldata:/data/mysql
        network_mode: host

    app:
        build: .
        container_name: nlwtogether
        ports:
            - 3333:3333
        volumes:
            - .:/usr/nlwtogether
        network_mode: host

volumes:
    mysqldata:
        driver: local